version: "3"

services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: apitest
    restart: unless-stopped
    ports:
      - ${API_PORT}:3001
    environment:
      - PORT=${API_PORT}
      - MONGODB_URL=mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - DRIVESHOW_ADDRESS=${DRIVESHOW_ADDRESS}
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - ${MONGODB_PORT}:27017
    command: mongod --noauth
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./client/build:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - api
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
